sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3121
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCYmsLqkrvHxPHKmcfS
    access-key-secret: e7McOFAnDEnWXdrcyO80PUqSXq2nBj
    bucket-name: take-out-heima
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx04ce8b3243e5d5c8
    secret: 7a9d3666e3b68bdb3d87c884db6c04dd
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    notify-url:
    refund-notify-url:
